image: repository.gridsum.com:8443/library/jdk-8-maven-node:latest
variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"
  MAVEN_CLI_OPTS: "--batch-mode --errors --show-version"

# 定义 stages
stages:
  - dev_deploy
  - test_deploy
  - 10.202.40.82
  - sonarqube


#部署开发环境
dev_deploy:
  tags:
    - java
  stage: dev_deploy
  script:
    - "mvn $MAVEN_CLI_OPTS clean package -DskipTests"
    - "sshpass -p $METASPACE_PASSWORD scp -o stricthostkeychecking=no webapp/target/atlas-webapp-*.war $DEPLOY_USER@$DEVELOP_SERVER_ID_1:$DEPLOY_PATH/metaspace.war"
    - "sshpass -p $METASPACE_PASSWORD ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEVELOP_SERVER_ID_1 \"$DEPLOY_HOME/bin/metaspace_stop.py && rm -rf $BACKUP_DIR && mv $DEPLOY_PATH/metaspace $BACKUP_DIR  && $DEPLOY_HOME/bin/metaspace_start.py\""
    - "sshpass -p $METASPACE_PASSWORD ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEVELOP_SERVER_ID_1 \"cd $BACKUP_DIR && rsync -av * $DEPLOY_PATH/metaspace --exclude WEB-INF\""
  when: manual
  artifacts:
    name: metaspace_dev
    expire_in: 1 week
    paths:
      - webapp/target/atlas-webapp-*.war

#部署测试环境
test_deploy:
  tags:
    - java
  stage: test_deploy
  script:
    - "mvn $MAVEN_CLI_OPTS clean package -DskipTests"
    - "sshpass -p $METASPACE_PASSWORD scp -o stricthostkeychecking=no webapp/target/atlas-webapp-*.war $DEPLOY_USER@$TEST_SERVER_ID_1:$DEPLOY_PATH/metaspace.war"
    - "sshpass -p $METASPACE_PASSWORD ssh -o stricthostkeychecking=no $DEPLOY_USER@$TEST_SERVER_ID_1 \"$DEPLOY_HOME/bin/metaspace_stop.py && rm -rf $BACKUP_DIR && mv $DEPLOY_PATH/metaspace $BACKUP_DIR  && $DEPLOY_HOME/bin/metaspace_start.py\""
    - "sshpass -p $METASPACE_PASSWORD ssh -o stricthostkeychecking=no $DEPLOY_USER@$TEST_SERVER_ID_1 \"cd $BACKUP_DIR && rsync -av * $DEPLOY_PATH/metaspace --exclude WEB-INF\""
  when: manual
  artifacts:
    name: metaspace_test
    expire_in: 1 week
    paths:
      - webapp/target/atlas-webapp-*.war
#部署测试环境
10.202.40.82:
  tags:
    - java
  stage: 10.202.40.82
  script:
    - "mvn $MAVEN_CLI_OPTS clean package -DskipTests"
    - "sshpass -p $METASPACE_PASSWORD scp -o stricthostkeychecking=no webapp/target/atlas-webapp-*.war $DEPLOY_USER@$TEST_SERVER_ID_2:$DEPLOY_PATH/metaspace.war"
    - "sshpass -p $METASPACE_PASSWORD ssh -o stricthostkeychecking=no $DEPLOY_USER@$TEST_SERVER_ID_2 \"$DEPLOY_HOME/bin/metaspace_stop.py && rm -rf $BACKUP_DIR && mv $DEPLOY_PATH/metaspace $BACKUP_DIR  && $DEPLOY_HOME/bin/metaspace_start.py\""
    - "sshpass -p $METASPACE_PASSWORD ssh -o stricthostkeychecking=no $DEPLOY_USER@$TEST_SERVER_ID_2 \"cd $BACKUP_DIR && rsync -av * $DEPLOY_PATH/metaspace --exclude WEB-INF\""
  when: manual
  artifacts:
    name: metaspace_test
    expire_in: 1 week
    paths:
      - webapp/target/atlas-webapp-*.war

sonarqube:
  tags:
    - java
  stage: sonarqube
  script: mvn clean verify sonar:sonar -DskipTests  -Dsonar.scm.disabled=True
  allow_failure: true
  when: manual
