image: repository.gridsum.com:8443/library/jdk-8-maven-node:latest
variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"
  MAVEN_CLI_OPTS: "--batch-mode --errors --show-version"

# 定义 stages
stages:
  - test
  - dev_deploy
  - test_deploy
  - sonarqube
  - 生成测试覆盖率报告
  - 删除测试覆盖率报告

# 单元测试
test:
  tags:
    - java
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean test
    - cat report/target/site/jacoco-aggregate/index.html
  only:
    - dev

#部署开发环境
dev_deploy:
  tags:
    - java
  stage: dev_deploy
  script:
    - "mvn $MAVEN_CLI_OPTS clean package -DskipTests"
    - "sshpass -p $METASPACE_PASSWORD ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEVELOP_SERVER_ID_1 \"rm -fr $DEPLOY_HOME/adapter/* \""
    - "sshpass -p $METASPACE_PASSWORD scp -o stricthostkeychecking=no webapp/target/atlas-webapp-*.war $DEPLOY_USER@$DEVELOP_SERVER_ID_1:$DEPLOY_PATH/metaspace.war"
    - "sshpass -p $METASPACE_PASSWORD scp -o stricthostkeychecking=no metaspace-adapter/target/pluginZip/*.zip $DEPLOY_USER@$DEVELOP_SERVER_ID_1:$DEPLOY_HOME/adapter/"
    - "sshpass -p $METASPACE_PASSWORD ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEVELOP_SERVER_ID_1 \"$DEPLOY_HOME/bin/metaspace_stop.py && rm -rf $BACKUP_DIR && mv $DEPLOY_PATH/metaspace $BACKUP_DIR  && $DEPLOY_HOME/bin/metaspace_start.py\""
    - "sshpass -p $METASPACE_PASSWORD ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEVELOP_SERVER_ID_1 \"cd $BACKUP_DIR && rsync -av * $DEPLOY_PATH/metaspace --exclude WEB-INF\""
  when: manual
  artifacts:
    name: metaspace_dev
    expire_in: 1 week
    paths:
      - webapp/target/atlas-webapp-*.war

#部署测试环境
test_deploy:
  tags:
    - java
  stage: test_deploy
  script:
    - "mvn $MAVEN_CLI_OPTS clean package -DskipTests"
    - "sshpass -p $METASPACE_PASSWORD ssh -o stricthostkeychecking=no $DEPLOY_USER@$TEST_SERVER_ID_1 \"rm -fr $DEPLOY_HOME/adapter/* \""
    - "sshpass -p $METASPACE_PASSWORD scp -o stricthostkeychecking=no webapp/target/atlas-webapp-*.war $DEPLOY_USER@$TEST_SERVER_ID_1:$DEPLOY_PATH/metaspace.war"
    - "sshpass -p $METASPACE_PASSWORD scp -o stricthostkeychecking=no metaspace-adapter/target/pluginZip/*.zip $DEPLOY_USER@$TEST_SERVER_ID_1:$DEPLOY_HOME/adapter/"
    - "sshpass -p $METASPACE_PASSWORD ssh -o stricthostkeychecking=no $DEPLOY_USER@$TEST_SERVER_ID_1 \"$DEPLOY_HOME/bin/metaspace_stop.py && rm -rf $BACKUP_DIR && mv $DEPLOY_PATH/metaspace $BACKUP_DIR  && $DEPLOY_HOME/bin/metaspace_start.py\""
    - "sshpass -p $METASPACE_PASSWORD ssh -o stricthostkeychecking=no $DEPLOY_USER@$TEST_SERVER_ID_1 \"cd $BACKUP_DIR && rsync -av * $DEPLOY_PATH/metaspace --exclude WEB-INF\""
  when: manual
  artifacts:
    name: metaspace_test
    expire_in: 1 week
    paths:
      - webapp/target/atlas-webapp-*.war

sonarqube:
  tags:
    - java
  stage: sonarqube
  script: mvn clean verify sonar:sonar -DskipTests  -Dsonar.scm.disabled=True
  allow_failure: true
  when: manual

生成测试覆盖率报告:
  tags:
    - java
  stage: 生成测试覆盖率报告
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release/'
      allow_failure: true
      when: manual
  script:
    - sshpass -p $PASSWORD_102 ssh -o stricthostkeychecking=no $USER_102@$SERVER_102 "/root/jacoco_report/metaspace/metaspace.sh $CI_COMMIT_BRANCH"


删除测试覆盖率报告:
  tags:
    - java
  stage: 删除测试覆盖率报告
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release/'
      allow_failure: true
      when: manual
  script:
    - sshpass -p $PASSWORD_102 ssh -o stricthostkeychecking=no $USER_102@$SERVER_102 "rm -rf /root/jacoco_report/metaspace/$CI_COMMIT_BRANCH"
