image: repository.gridsum.com:8443/gridsum/java:8
before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
# 定义 stages
stages:
  - test
  - cleanup
  - cleanup_build
# 定义 job
test:
  tags:
    - java
  stage: test
  script:
  - "mvn clean test"

cleanup-build:
  stage: cleanup_build
  script:
  - 'mvn clean'
  when: on_failure


cleanup:
  stage: cleanup
  script:
  - 'mvn clean'
  when: always

